### ISSUE TITLE
Not able to boot with 5.13.1

### ISSUE THREAD

**Issue by matthewoots** [avafinger/nanopi-r4s-minimal-image#2]
Hi @avafinger, thank you for making another awesome image. I have encounter an issue, after flashing the SD card, and running it on the R4S, the power LED lights up but not the system, I don't know whether I've done anything wrong, flashing went well `OK: Done - Raw Image created on sd card '/dev/sdb', remove and boot.` and also `rootfs` and `boot` partitions appeared.

I've use the release that you have provided (https://github.com/avafinger/nanopi-r4s-minimal-image/commit/4db3dee71a3658be4436da46e82222e54dcea864) 

Thank you in advance!

**Comment by avafinger** [comment]
> after flashing the SD card, and running it on the R4S, the power LED lights up but not the system

This is typically related to the power input.
I use this one: https://www.friendlyarm.com/index.php?route=product/product&product_id=238&search=5v&description=true&sub_category=true
RK3399 is a powerful chip.


You can try a few things:
1. check if the sd card is ok
  sudo umount /media/ * / * (unmount the sd card)
  sudo fsck.ext4 -f /dev/sdb1
  sudo fsck.ext4 -f /dev/sdb2

if you get any error, re-write the sd-card and check again

2. Find a better Power adapter
3. If you have a TTL debug it is easier to find out want is going on. This is an indispensable tool.
   https://www.friendlyarm.com/index.php?route=product/product&product_id=178&search=TTL&description=true&sub_category=true

**Comment by matthewoots** [comment]
The power input I used is rated 4A too (2) and tested (1), all are without error
```
nvidia@nvidia-msi:~/Downloads/R4S_5-13-1$ sudo fsck.ext4 -f /dev/sdb1
e2fsck 1.44.1 (24-Mar-2018)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
boot: 19/30720 files (10.5% non-contiguous), 10240/30720 blocks
nvidia@nvidia-msi:~/Downloads/R4S_5-13-1$ sudo fsck.ext4 -f /dev/sdb2
e2fsck 1.44.1 (24-Mar-2018)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
rootfs: 70167/3858432 files (0.2% non-contiguous), 1661567/15410688 blocks
```
TTL debug shows receiving of packets, but then it is publishing garbage when I `screen /dev/ttyUSB0 1500000 8N1`

**Comment by avafinger** [comment]
That means the u-boot cannot be loaded from the micro sd card. Even so, you should see the rockchip trying to load from ethernet and stopping at this point. Maybe the sd card was not even detected, so nothing to load, nothing to show.

I have the best experience with sandisk ultra 32GB and 64GB.
If you have a spare sd card, please, try https://github.com/avafinger/nanopi-r4s-minimal-image/releases/tag/v1 which has older u-boot and loader.

**Comment by matthewoots** [comment]
Hi @avafinger, thanks for helping with the debug, I tried https://github.com/avafinger/nanopi-r4s-minimal-image/releases/tag/v1 but to no avail. The SD card works fine, I'm using the Lexar 64GB Blue series that is comparable to the ultra. I've flashed with `armbian focal` and it works (https://www.armbian.com/nanopi-r4s/) green flashing light on system and solid green for WAN. This would rule out problem in the `Power, WAN and SD card` setup. Probably I'll need to get the u-boot up, any leads for it, or is there an `img` i can flash using maybe `BalenaEtcher`?

**Comment by avafinger** [comment]
Yes, you could try with BalenaEtcher or ImageWriter or similar.
Make sure you inserted the sd card to the end.

Tried minicom?

**Comment by matthewoots** [comment]
Alright, but what should I give to BalenaEtcher to flash? Since the release contains several contents, I know the main ones are the boot and rootfs but then there are several other imgs, like uboot etc.

**Comment by avafinger** [comment]
Ahh, forgot it is not IMG, sorry.
I will provide an IMG and then you can have a try on that.

**Comment by nabrog87** [comment]
hello, can you please tell me what is the source of your kernel?
I'm trying to build my own kernel  but I can't find some latest sources.
I have installed proxmox over armbian bullseye and i need to enable some kernel modules.
TY

**Comment by avafinger** [comment]
Sources:
https://cdn.kernel.org/pub/linux/kernel/v5.x/ (5.10)
with patches from FriendlyElec for the second ethernet:
https://github.com/friendlyarm/kernel-rockchip/commits/nanopi-r2-v5.10.y

> I have installed proxmox over armbian bullseye and i need to enable some kernel modules

If you have the armbian kernel you need to stick with that kernel since it uses different initramfs than what I have used.

To build a kernel (or any other kernel) for the current image you can follow the instructions here:
https://github.com/avafinger/nanopi-m4-ubuntu-base-minimal#mainline-kernel-510

**Comment by matthewoots** [comment]
Hi @avafinger, do you have any leads on the img? or is there anyway I can try to get the img together from the files above? Thanks in advance

**Comment by avafinger** [comment]
oops, was busy and forgot to make one this weekend. I will try to make IMG tonight.

**Comment by avafinger** [comment]
@matthewoots 

Please, try this one:
https://github.com/avafinger/nanopi-r4s-minimal-image/releases/tag/v2-pre-built-img

**Comment by matthewoots** [comment]
Hi @avafinger thank you so much for the **pre built img**, the **sys light** is green so i guess all is working, i'll close this issue first and test it out with a screen or headless soon.
