### ISSUE TITLE
how to burn the image to R4SE with emmc?

### ISSUE THREAD

**Issue by leechaowen** [avafinger/nanopi-r4s-minimal-image#7]
hi,how to burn the image to R4SE with emmc not SD card? Thanks.

**Comment by avafinger** [comment]
I think you need to find out eMMC device /dev/mmcblk? and change the script to write there.
You also need to change /boot/ arguments and /etc/fstab to point to eMMC.

Note /dev/mmcblk?? may change if you boot from SD CARD or eMMC
